config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :locations do
    resources :readings
  end
  resources :users
  root 'locations#index'

  get 'map' => 'maps#view'

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
  has_many :readings, dependent: :destroy
  validates_presence_of :name
  validates :name, uniqueness: true
  validates_presence_of :lat, :long

  LOCATION_TYPES = [:mine, :test_site]

end

app/models/reading.rb
class Reading < ActiveRecord::Base
  belongs_to :location
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :readings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception




end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

    before_action :authenticate_user!, except: [:index]

  def new
    @location = Location.new
    @types = [["Mine", "mine"], ["Test Site", "test"]]
  end

  def create
    @location = Location.new(location_params)
    @location.user_id = current_user.id

    if @location.save
      flash[:notice] = "location added!"
      redirect_to locations_path
    else
      render "locations/new"
    end
  end

  def index
    @locations = Location.all
  end

  def update
  end



  def edit
  end

  private

    def location_params
      params.require(:location).permit(:name, :description, :lat, :long, :location_type)
    end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def view
    gon.locations = []
    Location.all.each do |l|
      loc = {name: l.name, lat: l.lat, long: l.long, type: l.location_type}
      gon.locations.push(loc)
    end
  end

  private


end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController

    before_action :authenticate_user!, except: [:index]

  def new
    @location = Location.find(params[:location_id])
    @reading = Reading.new
  end

  def create
    @reading = Reading.new(reading_params)
    @reading.user_id = current_user.id
    @location = Location.find(params[:location_id])
    @reading.location_id = @location.id  #need to test this
    if @reading.save
      flash[:notice] = "reading added!"
      redirect_to locations_path
    else
      render "readings/new"
    end
  end

  def index
    @location = Location.find(params[:location_id])
    @readings = Reading.where(location_id: @location.id)
  end

  def update
  end

  def edit
  end

  private

    def reading_params
      params.require(:reading).permit(:location_id, :user_id, :ph, :conductivity, :date_observed,
                                      :time_observed, :weather, :water_temp, :TDS, :observations)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def new
  end

  def index
  end

  def update
  end

  def create
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= include_gon %>
  <title>WaterData</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAuBy0caNu5eU25w8-IvFx8RFtL2A1GwXQ"></script
</head>
  <body>
      <nav class = "navbar navbar-default">
        <div class = "container-fluid">
          <div class = "navbar-header">
            <button type="button" class = "navbar-toggle collapsed" data-toggle="collapse"
              data-target="#navbar-content" aria-expanded = "false">
              <span class = "sr-only">Toggle navigation</span>
              <span class = "icon-bar"></span>
              <span class = "icon-bar"></span>
              <span class = "icon-bar"></span>
            </button>
            <%= link_to "Home", root_path, class: "navbar-brand" %>
          </div>
          <div class = "collapse navbar-collapse" id = "navbar-content">
            <ul class = "nav navbar-nav">
              <li><%= link_to "Add Location", new_location_path if user_signed_in? %></li>
              <li><%= link_to "Map", map_path %></li>
            </ul>
            <ul class = "nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li class="dropdown">
                    <%= link_to current_user.email, user_path(current_user), class: "dropdown-toggle pull-right",
                                    "data-toggle": "dropdown" %>
                  <ul class = "dropdown-menu">
                    <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign in", new_user_session_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class = "container">
        <div>
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
        </div>
        <%= yield %>
      </div>

  </body>
</html>

app/views/locations/edit.html.erb
<h1>Locations#edit</h1>
<p>Find me in app/views/locations/edit.html.erb</p>

app/views/locations/index.html.erb
<h1>All Locations</h1>
<div class = "row">
  <table class = "table table-striped">
    <thead>
      <tr>
        <th>Unique Id</th>
        <th>Location Name</th>
        <th>Location Description</th>
        <th>Readings</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @locations.each do |location| %>
        <tr>
          <td><%= location.id %></td>
          <td><%= location.name %></td>
          <td><%= location.description %></td>
          <td><%= link_to location.readings.count, location_readings_path(location) %></td>
          <td><%= link_to "Add a reading", new_location_reading_path(location) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/locations/new.html.erb
<div class = "row">
  <div class = "col-xs-6">
    <h1>Add a location</h1>
    <%= form_for @location do |f| %>
      <div class = "form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control" %>
        <%= f.label "Latitude" %>
        <%= f.text_field :lat, class: "form-control" %>
        <%= f.label "Longitude" %>
        <%= f.text_field :long, class: "form-control" %>
        <%= f.label "Type of Site" %>
        <%= f.select :location_type, @types, {}, class: "form-control" %>
        <%= render "shared/error_messages", object: f.object %>
        <%= f.submit "Add location", class: "btn btn-success" %>
      </div>

    <% end %>
  </div>
  <div class = "col-xs-6">
    <div id = "new-location-map-container">
      <div id = "new-location-map-canvas"></div>
    </div>
  </div>
</div>
<%= javascript_tag "newLocation()" %>

app/views/locations/update.html.erb
<h1>Locations#update</h1>
<p>Find me in app/views/locations/update.html.erb</p>

app/views/maps/view.html.erb
<h1>Map of all locations</h1>

<div id = "map-container">
  <div id = "map-canvas"></div>
</div>
<%= javascript_tag "mapView()" %>

app/views/maps/view.js.erb
  var locations = '<%= @locations %>';

app/views/readings/create.html.erb
<h1>Readings#create</h1>
<p>Find me in app/views/readings/create.html.erb</p>

app/views/readings/edit.html.erb
<h1>Readings#edit</h1>
<p>Find me in app/views/readings/edit.html.erb</p>

app/views/readings/index.html.erb
<h1>Readings for <%= @location.name %></h1>
<div class = "row">
  <table class = "table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Weather</th>
        <th>Water Temperature</th>
        <th>pH</th>
        <th>Conductivity</th>
        <th>TDS</th>
        <th>Observations</th>
      </tr>
    </thead>
    <tbody>
    <% @readings.each do |reading| %>
    <tr>
      <td><%= reading.date_observed %></td>
      <td><%= reading.time_observed %></td>
      <td><%= reading.weather %></td>
      <td><%= reading.water_temp %></td>
      <td><%= reading.ph %></td>
      <td><%= reading.conductivity %></td>
      <td><%= reading.TDS %></td>
      <td><%= reading.observations %></td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/readings/new.html.erb
<div class = "col-xs-6 col-xs-offset-3">
  <h1>Add a reading for <%= @location.name %></h1>
  <%= form_for [@location, @reading] do |f| %>
    <div class = "form-group">
      <div>
        <%= f.label :date_observed %>
        <%= f.date_select :date_observed, class: "form-control" %>
      </div>
      <div>
        <%= f.label :time_observed %>
        <%= f.time_select :time_observed, class: "form-control" %>
      </div>
      <div>
        <label>pH</label>
        <%= f.text_field :ph, class: "form-control" %>
      </div>
      <div>
        <%= f.label :conductivity %>
        <%= f.text_field :conductivity, class: "form-control" %>
      </div>
      <div>
        <%= f.label :water_temp %>
        <%= f.text_field :water_temp, class: "form-control" %>
      </div>
      <div>
        <%= f.label :TDS %>
        <%= f.text_field :TDS, class: "form-control" %>
      </div>
      <div>
        <%= f.label :observations %>
        <%= f.text_area :observations, class: "form-control" %>
      </div>
      <div>
        <%= f.label :weather %>
        <%= f.text_area :weather, class: "form-control" %>
      </div>
      <div>
        <%= f.submit "Add reading", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/readings/update.html.erb
<h1>Readings#update</h1>
<p>Find me in app/views/readings/update.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>